############################################################
#
# Tomcat 配置 端口号用8088!!
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  application:
    name: foodie-item-service  #微服务注意：该微服务在注册中心中的名字
  ## Feign 如果接口B继承接口A，而它们的@FeignClient的服务名称相同，则允许覆盖(如果不允许，则就产生冲突)
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev #和prod切换
  datasource:  # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    # url: jdbc:mysql://localhost:3306/foodMart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    # username: root
    # password: root1234
    hikari:
     connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
     minimum-idle: 5 # 最小连接数
     maximum-pool-size: 20 # 最大连接数
     auto-commit: true # 自动提交
     idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
     pool-name: DateSourceHikariCP # 连接池名字
     max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
     connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 # 文件上传大小限制为500KB
      max-request-size: 512000 # 请求大小限制为500KB
  session:
    store-type: redis #指定会话所保存的介质
############################################################
#
# mybatis 配置(微服务注意：改造在这里记得更改type-aliases-package路径)
#
############################################################
mybatis:
  type-aliases-package: com.rlj.item.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台输出日志的实现
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
 mappers: com.rlj.my.mapper.MyMapper
 not-empty: false
 identity: MYSQL
#分页插件配置
pagehelper:
  helperDialect: mysql            #告知我们所使用的数据库种类
  supportMethodsArguments: true   #允许开启一些pagehelper的配置