#1、端口
server:
 port: 10004  # 微服务注意：后续要启动很多端口，这里就从10001开始
#2、数据源改动
spring:
  datasource:
    # 数据源的相关配置(微服务注意：每个服务都应该有对应的数据源)
    url: ${mariadb.url}
    password: ${mariadb.password}
    username: ${mariadb.username}
  redis:
    database: 1   #database数量，16以内，默认是0
    host: localhost   #我们所使用的Redis所在的主机地址，这虚拟机的，若是我们的本机那就是127.0.0.1  可以用虚拟机的192.168.218.22
    port: 6379
    timeout: 500
    # password: rlj   #Redis所在主机的配置文件中配置的密码

#3、开发环境我们的日志打印照旧
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台输出日志的实现

#4、开启actuator，暴露信息以供hystrix的turbine接收(已经在Gitee配置中心上配置)